apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetaks-app
  labels:
    app: dotnetaks
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dotnetaks
  template:
    metadata:
      labels:
        app: dotnetaks
    spec:
      containers:
      - name: dotnetaks-app
        image: ${CONTAINER_REGISTRY}/dotnetaks-app:${IMAGE_TAG}
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
        volumeMounts:
        - name: config-volume
          mountPath: /app/appsettings.json
          subPath: appsettings.json
      volumes:
      - name: config-volume
        configMap:
          name: dotnetaks-config