apiVersion: v1
kind: Service
metadata:
  name: dotnetaks-service
  labels:
    app: dotnetaks
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: dotnetaks