name: Build and Deploy to AKS

on:
  push:
    branches: [ "main" ]
    paths:
      - 'DotNetAksApp/**'
  workflow_dispatch:  # Allows manual triggering

env:
  REGISTRY_NAME: your-acr-name  # Change this to your Azure Container Registry name
  CLUSTER_NAME: your-aks-cluster  # Change this to your AKS cluster name
  CLUSTER_RESOURCE_GROUP: your-resource-group  # Change this to your resource group name
  APP_NAME: dotnetaks-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up kubelogin for non-interactive login
      uses: azure/use-kubelogin@v1
      with:
        kubelogin-version: 'v0.0.25'

    - name: Login to ACR
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push image to ACR
      uses: docker/build-push-action@v4
      with:
        context: ./DotNetAksApp
        push: true
        tags: ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}

    - name: Get AKS credentials
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
        cluster-name: ${{ env.CLUSTER_NAME }}

    - name: Deploy to AKS
      uses: azure/k8s-deploy@v4
      with:
        namespace: default
        manifests: |
          ./DotNetAksApp/k8s/deployment.yaml
          ./DotNetAksApp/k8s/service.yaml
        images: |
          ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
        strategy: canary
        percentage: 20